name: camilamuebleria
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/image/c_1.webp
    - assets/image/c_2.webp
    - assets/image/c_3.webp
    - assets/image/banner_1.png
    - assets/image/banner_2.png
    - assets/image/banner_3.png
    - assets/card/iphone_icon.png
    - assets/card/laptop_icon.png
    - assets/card/television_icon.png
    - assets/card/refrigerador_icon.png
    - assets/image/camila_logo_bg.png
